[package]
name = "polyplets"
version = "0.3.2"
description = "Security primitives to verify origin of service calls in Fluence network"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
documentation = "https://docs.rs/polyplets"
repository = "https://github.com/fluencelabs/aquavm/tree/master/crates/air-lib/polyplets"
keywords = ["fluence", "air", "webassembly", "security", "authorization"]
categories = ["authentication"]

[lib]
name = "polyplets"
path = "src/lib.rs"

[dependencies]
marine-macro = "0.7.1"
marine-rs-sdk-main = "0.7.1"

serde = { version = "1.0.155", features = ["rc", "derive"] }
