[package]
name = "air-test-utils"
version = "0.4.5"
description = "Test utils for the AIR interpreter"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/fluencelabs/aquavm"
documentation = "https://docs.rs/air-test-utils"
keywords = ["fluence", "air", "webassembly", "security", "authorization"]
categories = ["wasm"]

[lib]
name = "air_test_utils"
path = "src/lib.rs"

[dependencies]
aquavm-air = { path = "../../../air" }
air-interpreter-cid = { version = "0.2.0", path = "../interpreter-cid" }
air-interpreter-data = { version = "0.6.3", path = "../interpreter-data" }
air-interpreter-interface = { version = "0.12.1", path = "../interpreter-interface" }
avm-interface = { version = "0.28.2", path = "../../../avm/interface" }
avm-server = { version = "0.30.1", path = "../../../avm/server" }
marine-rs-sdk = "0.7.1"

fstrings = "0.2.3"
object-pool = "0.5.4"
once_cell = "1.17.1"
semver = "1.0.17"
serde_json = "1.0.94"
serde = { version = "1.0.155", features = ["derive"] }

[dev-dependencies]
maplit = "1.0.2"

[features]
test_with_native_code = []
