[package]
name = "air-interpreter-data"
description = "Data format of the AIR interpreter"
version = "0.6.3"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/fluencelabs/aquavm"
documentation = "https://docs.rs/air-interpreter-data"
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_interpreter_data"
path = "src/lib.rs"

[dependencies]
air-utils = { version = "0.1.0", path = "../utils" }
aquavm-air-parser = { version = "0.7.3", path = "../air-parser" }
air-interpreter-interface = { version = "0.12.1", path = "../interpreter-interface" }
air-interpreter-cid = { version = "0.2.0", path = "../interpreter-cid" }
polyplets = { version = "0.3.2", path = "../polyplets" }

serde = {version = "1.0.155", features = ["derive", "rc"]}
serde_json = "1.0.94"
semver = { version = "1.0.17", features = ["serde"] }
once_cell = "1.17.1"
tracing = "0.1.37"
